---
name: Devel-Autoflush
version: 0.02
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: Set autoflush from the command line
license: apache
resources:
  license: http://apache.org/licenses/LICENSE-2.0
requires:
  perl: 5.004
build_requires:
  IO::CaptureOutput: 1.08
  Test::More: 0.62
provides:
  Devel::Autoflush:
    file: lib/Devel/Autoflush.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
